//	var Creador = '<?php echo $usuario['id_incapacidades']; ?>'
$(function() {
	var x ='';
	var pagos = {
		inicio: function () {
			pagos.GetTotal();
			pagos.AddClicks();
			pagos.TablaDetalle();
		},		
		GetTotal: function()
		{
			var total = 0;
			$('#tabla-detalle tr').find("td.money-values").each(function(indice, elemento) {

				total += parseInt($(elemento).text());
				$('#totalinc').text(total);

			}); 
		},
		AddClicks: function()
		{
			$('.boton-volver').on("click", function(){

				window.location.href = "pages/pagos/gestionar.php";

			});
		},TablaDetalle : function()
		{
			x = $('#tabla-detalle').DataTable({
				dom: 'Bfrtip',
				searching: true,
				paging: false,
				ordering: true,
				info:     true,
				buttons: [
				'csv', 'excel', 
				{
					extend: 'pdfHtml5',
					text: 'PDF',
					customize: function ( doc ) {
                // Splice the image in after the header, but before the table
                doc.content.splice( 1, 0, {
                	margin: [ 0, 0, 0, 12 ],
                	alignment: 'left',
                	image: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAEm0lEQVRYhb2XXWwUVRTHf3dm2m4LrW1YUSkIJkuVVE1hw0cjIBFFEwMK4YkHLLGJig+CSEltCGIFw4cfm1R9sCGmhgRNeFBeJApopDyUuDxIxFQKFKgtUArdbbf7MTPHh90psDvddqFykpud3Jy5/98599xzZxV3a42zS9HZjkYFmtpMXfD03Syjcn6jYbaBTi0GjejKiw7omGg0A1vZFOz9/wC2VC1BJ4Cunk4Jg6649cxNFI2YNPFeMD5+AHVVM7DZg8bqTNG0Zw1A2hE2szH442hLa6M5rHrDtx6RMyhWY0PmEBBSQ1JhqQo09QOfzzl8zwBfdF974cClHk9FPJVRR2hY1AVKxIF57p4BAJ6NRDlyvouPrl6n1LTSxNKAGM5CcowHAIABvH4zxIlzl1nXF0J3Uu+AKCCPZB2MQThnAMfKbJudV67zS8dlFoUjSeFCBR5Ay/1U5wzg2BOxBN+d72F/wQUey4/lFPW4AEAy+Jfpp42/+JDLFGPdXwDHChA2cIVTnGYtvWhOId4vAMcmY9JEJ79yhmrC4wAQ8Oe3T5rmzRWkiiF+op1vrl2ji9pHs/m6V07AD7AC+GRV+fu+5d29LDyxl4mDVzNcC6vDaEX2HXMSNYj/XEX82FNg6RFgL7CrnObI6AAB/5PAZ8DzACunNlBRXI2RiDD3j6/xn9qHYcVcAUTAPOkjdmguEpqQvvJFYAtwoJxmF4CA3ws0ArUk+w63AzhWHOpiUetuZnYcTraAFIDV+SDRg9XYnZMzYkqz48A75TQHkwABfz6wHtgGlKZ7pwM4Vt7VxpLfdzLtodPEj/gx22aSw+1uA/uABp2XHtkJNKKUx81zVsliJhVMy5i/WTyFb6evpHJHlz2x3asU+ljFEUQdrOyb8+aKDmWAyseS5LVqMGo7FREuxCxa++OELGHAjmk3VDdFUoaHUtQoB6ujLEr9sk5ap4dB0Ib3GguIAYYNHvcLpS9h0xqKcymW1vGUEFF9RCVEkXjJZwIqbTtiuk3T/B6a5ncT1yW5CTjF5jQuERgCBgWKgMLUy7ZwMhznz0Eza4+zlcmA6sGQQiaIF4MCAI5PD1G/rJNzZbGMd4yMGScbN2wYgLNlJscHI0RtV09XM9UQ/VwiWlRs71oa0Q5W9qXqMy2rIhi3onf5jcM//SZ5JWMXBzA14ftnEnz54r+EhrKQy0gZyOEySbcTFSa7V8Y497Cd3NJs38aSUQN3r3/Ra7PnlSi/VVp3ZlrPcqpGzkDKxtBXBj3Cp8uj7F+cIOG2WjYFGwxEDiG8ijDDoRqj2UDL27U3znSXJhoA90oZqT+JHAW+0ng3eBRLZiGyFWFgGCI7SBtQHa7xrevedmw38DjQwvDpvh1ApQ16UbxGXC2l/tTZO5P8wewpmOzClDWYaGjgmVpHXsk8x6MHqAdawjW+TLGAfwEQAOalorRBpVqjgNCCzabb/z+67/KWqnlYBNBYkAKIA03A9nCNL5Q1NwG/BqwFPkZkMkppiLQjvMXG4NF095HLrK5KA9Z4yjcsz3tg4bZwje/vrMKZICXYshVFFIsdbApG3dz+A/Py0oPaSa/CAAAAAElFTkSuQmCC'
                } ),
                doc.content.splice( 2, 0, {
                	margin: [ 0, 0, 0, 12 ],
                	alignment: 'left',
                	text: [
                	{ text: $('.textodetalle').text(), fontSize: 15 },
                	''
                	]
                } ),doc.content.splice( 3, 0, {
                	margin: [ 0, 0, 0, 12 ],
                	alignment: 'left',
                	text: [
                	{ text: 'Fecha : ', fontSize: 13 },
                	$('.fechapago').val()
                	]
                } ),
                doc.content.splice( 4, 0, {
                	margin: [ 0, 0, 0, 12 ],
                	alignment: 'left',
                	text: [
                	{ text: 'Valor : ', fontSize: 13 },
                	$('.valorpago').val()
                	]
                } ),doc.content.splice( 5, 0, {
                	margin: [ 0, 0, 0, 12 ],
                	alignment: 'left',
                	text: [
                	{ text: 'Eps : ', fontSize: 13 },
                	$('.epspago').val()
                	]
                } )
                // Data URL generated by http://dataurl.net/#dataurlmaker
            }
        },
        {
        	extend: 'print',
        	text: 'Imprimir',
        	messageTop: 'The information in this table is copyright to Sirius Cybernetics Corp.'
        }
        ],
        order: [[ 2, "desc" ]]

    });

		}
	};
	$(document).ready(function () {

		pagos.inicio();

	});

});