//	var Creador = '<?php echo $usuario['id_incapacidades']; ?>'
$(function() {
	var t ='';
	var pagos = {
		inicio: function () {
			pagos.AddClicks();
			pagos.Cargar();
			pagos.recargar();
			pagos.Tabla();
			pagos.TablaDetalle();

			$('.filtrar-boton').trigger('click');
		},		
		AddClicks: function()
		{
			
		},
		recargar: function () 
		{
			pagos.enviarDatos();
			pagos.cargarModal();
			pagos.AgregarItem();
			pagos.MostrarDetalles();
		},
		TablaDetalle : function()
		{
			x = $('#tabla-detalle').DataTable({
				dom: 'Bfrtip',
				searching: true,
				paging: false,
				ordering: true,
				info:     true,
				buttons: [
				'csv', 'excel', 
				{
					extend: 'pdfHtml5',
					text: 'PDF',
					customize: function ( doc ) {
                // Splice the image in after the header, but before the table
                doc.content.splice( 1, 0, {
                	margin: [ 0, 0, 0, 12 ],
                	alignment: 'left',
                	image: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAEm0lEQVRYhb2XXWwUVRTHf3dm2m4LrW1YUSkIJkuVVE1hw0cjIBFFEwMK4YkHLLGJig+CSEltCGIFw4cfm1R9sCGmhgRNeFBeJApopDyUuDxIxFQKFKgtUArdbbf7MTPHh90psDvddqFykpud3Jy5/98599xzZxV3a42zS9HZjkYFmtpMXfD03Syjcn6jYbaBTi0GjejKiw7omGg0A1vZFOz9/wC2VC1BJ4Cunk4Jg6649cxNFI2YNPFeMD5+AHVVM7DZg8bqTNG0Zw1A2hE2szH442hLa6M5rHrDtx6RMyhWY0PmEBBSQ1JhqQo09QOfzzl8zwBfdF974cClHk9FPJVRR2hY1AVKxIF57p4BAJ6NRDlyvouPrl6n1LTSxNKAGM5CcowHAIABvH4zxIlzl1nXF0J3Uu+AKCCPZB2MQThnAMfKbJudV67zS8dlFoUjSeFCBR5Ay/1U5wzg2BOxBN+d72F/wQUey4/lFPW4AEAy+Jfpp42/+JDLFGPdXwDHChA2cIVTnGYtvWhOId4vAMcmY9JEJ79yhmrC4wAQ8Oe3T5rmzRWkiiF+op1vrl2ji9pHs/m6V07AD7AC+GRV+fu+5d29LDyxl4mDVzNcC6vDaEX2HXMSNYj/XEX82FNg6RFgL7CrnObI6AAB/5PAZ8DzACunNlBRXI2RiDD3j6/xn9qHYcVcAUTAPOkjdmguEpqQvvJFYAtwoJxmF4CA3ws0ArUk+w63AzhWHOpiUetuZnYcTraAFIDV+SDRg9XYnZMzYkqz48A75TQHkwABfz6wHtgGlKZ7pwM4Vt7VxpLfdzLtodPEj/gx22aSw+1uA/uABp2XHtkJNKKUx81zVsliJhVMy5i/WTyFb6evpHJHlz2x3asU+ljFEUQdrOyb8+aKDmWAyseS5LVqMGo7FREuxCxa++OELGHAjmk3VDdFUoaHUtQoB6ujLEr9sk5ap4dB0Ib3GguIAYYNHvcLpS9h0xqKcymW1vGUEFF9RCVEkXjJZwIqbTtiuk3T/B6a5ncT1yW5CTjF5jQuERgCBgWKgMLUy7ZwMhznz0Eza4+zlcmA6sGQQiaIF4MCAI5PD1G/rJNzZbGMd4yMGScbN2wYgLNlJscHI0RtV09XM9UQ/VwiWlRs71oa0Q5W9qXqMy2rIhi3onf5jcM//SZ5JWMXBzA14ftnEnz54r+EhrKQy0gZyOEySbcTFSa7V8Y497Cd3NJs38aSUQN3r3/Ra7PnlSi/VVp3ZlrPcqpGzkDKxtBXBj3Cp8uj7F+cIOG2WjYFGwxEDiG8ijDDoRqj2UDL27U3znSXJhoA90oZqT+JHAW+0ng3eBRLZiGyFWFgGCI7SBtQHa7xrevedmw38DjQwvDpvh1ApQ16UbxGXC2l/tTZO5P8wewpmOzClDWYaGjgmVpHXsk8x6MHqAdawjW+TLGAfwEQAOalorRBpVqjgNCCzabb/z+67/KWqnlYBNBYkAKIA03A9nCNL5Q1NwG/BqwFPkZkMkppiLQjvMXG4NF095HLrK5KA9Z4yjcsz3tg4bZwje/vrMKZICXYshVFFIsdbApG3dz+A/Py0oPaSa/CAAAAAElFTkSuQmCC'
                } );
                // Data URL generated by http://dataurl.net/#dataurlmaker
            }
        },
        {
        	extend: 'print',
        	text: 'Imprimir',
        	messageTop: 'The information in this table is copyright to Sirius Cybernetics Corp.'
        }
        ],
        order: [[ 2, "desc" ]]

    });

		},

		Tabla : function()
		{
			t = $('#tabla-pagos').DataTable({
				dom: 'Bfrtip',
				searching: true,
				paging: false,
				ordering: true,
				info:     true,
				buttons: [
				'csv', 'excel', {
					extend: 'pdfHtml5',
					text: 'PDF',
					customize: function ( doc ) {
                // Splice the image in after the header, but before the table
                doc.content.splice( 1, 0, {
                	margin: [ 0, 0, 0, 12 ],
                	alignment: 'left',
                	image: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAEm0lEQVRYhb2XXWwUVRTHf3dm2m4LrW1YUSkIJkuVVE1hw0cjIBFFEwMK4YkHLLGJig+CSEltCGIFw4cfm1R9sCGmhgRNeFBeJApopDyUuDxIxFQKFKgtUArdbbf7MTPHh90psDvddqFykpud3Jy5/98599xzZxV3a42zS9HZjkYFmtpMXfD03Syjcn6jYbaBTi0GjejKiw7omGg0A1vZFOz9/wC2VC1BJ4Cunk4Jg6649cxNFI2YNPFeMD5+AHVVM7DZg8bqTNG0Zw1A2hE2szH442hLa6M5rHrDtx6RMyhWY0PmEBBSQ1JhqQo09QOfzzl8zwBfdF974cClHk9FPJVRR2hY1AVKxIF57p4BAJ6NRDlyvouPrl6n1LTSxNKAGM5CcowHAIABvH4zxIlzl1nXF0J3Uu+AKCCPZB2MQThnAMfKbJudV67zS8dlFoUjSeFCBR5Ay/1U5wzg2BOxBN+d72F/wQUey4/lFPW4AEAy+Jfpp42/+JDLFGPdXwDHChA2cIVTnGYtvWhOId4vAMcmY9JEJ79yhmrC4wAQ8Oe3T5rmzRWkiiF+op1vrl2ji9pHs/m6V07AD7AC+GRV+fu+5d29LDyxl4mDVzNcC6vDaEX2HXMSNYj/XEX82FNg6RFgL7CrnObI6AAB/5PAZ8DzACunNlBRXI2RiDD3j6/xn9qHYcVcAUTAPOkjdmguEpqQvvJFYAtwoJxmF4CA3ws0ArUk+w63AzhWHOpiUetuZnYcTraAFIDV+SDRg9XYnZMzYkqz48A75TQHkwABfz6wHtgGlKZ7pwM4Vt7VxpLfdzLtodPEj/gx22aSw+1uA/uABp2XHtkJNKKUx81zVsliJhVMy5i/WTyFb6evpHJHlz2x3asU+ljFEUQdrOyb8+aKDmWAyseS5LVqMGo7FREuxCxa++OELGHAjmk3VDdFUoaHUtQoB6ujLEr9sk5ap4dB0Ib3GguIAYYNHvcLpS9h0xqKcymW1vGUEFF9RCVEkXjJZwIqbTtiuk3T/B6a5ncT1yW5CTjF5jQuERgCBgWKgMLUy7ZwMhznz0Eza4+zlcmA6sGQQiaIF4MCAI5PD1G/rJNzZbGMd4yMGScbN2wYgLNlJscHI0RtV09XM9UQ/VwiWlRs71oa0Q5W9qXqMy2rIhi3onf5jcM//SZ5JWMXBzA14ftnEnz54r+EhrKQy0gZyOEySbcTFSa7V8Y497Cd3NJs38aSUQN3r3/Ra7PnlSi/VVp3ZlrPcqpGzkDKxtBXBj3Cp8uj7F+cIOG2WjYFGwxEDiG8ijDDoRqj2UDL27U3znSXJhoA90oZqT+JHAW+0ng3eBRLZiGyFWFgGCI7SBtQHa7xrevedmw38DjQwvDpvh1ApQ16UbxGXC2l/tTZO5P8wewpmOzClDWYaGjgmVpHXsk8x6MHqAdawjW+TLGAfwEQAOalorRBpVqjgNCCzabb/z+67/KWqnlYBNBYkAKIA03A9nCNL5Q1NwG/BqwFPkZkMkppiLQjvMXG4NF095HLrK5KA9Z4yjcsz3tg4bZwje/vrMKZICXYshVFFIsdbApG3dz+A/Py0oPaSa/CAAAAAElFTkSuQmCC'
                } );
                // Data URL generated by http://dataurl.net/#dataurlmaker
            }
        }, {
        	extend: 'print',
        	text: 'Imprimir',
        	messageTop: 'The information in this table is copyright to Sirius Cybernetics Corp.'
        }
        ],
        order: [[ 7, "desc" ]]

    });

		},
		Filtrar : function()
		{
			var where="WHERE 1=1 ";

			if ($('.f-fechapago').val().length>0)
			{
				where+= ' AND pg.fecha_pago = "'+$('.f-fechapago').val()+'"'; 
			}
			if ($('.select-estado option:selected').val().length>0)
			{
				where+= ' AND pg.estado="'+$('.select-estado option:selected').val()+'"'; 
			}
			if ($('.select-eps option:selected').val().length>0)
			{
				where+= ' AND pg.id_eps='+$('.select-eps option:selected').val()+' '; 
			}

			return where;
		},
		Cargar : function()
		{
			var $demoMaskedInput = $('.demo-masked-input');

		    //Date
		    $demoMaskedInput.find('.date').inputmask('yyyy-mm-dd', { placeholder: '____-__-__' });

		},
		enviarDatos: function () {
			$('.filtrar-boton').off('click').on('click', function () {

				var total =0;
				$.ajax({
					url: 'pages/pagos/peticiones/peticiones.php',
					type: 'POST',
					data: {
						bandera: "filtrar",
						where: pagos.Filtrar()

					},
					success: function (resp) {

						var resp = $.parseJSON(jQuery.trim(resp));;
						if (resp.salida === true && resp.mensaje === true) {
							t.row($('#tabla-pagos').parents('tr') ).clear().draw();

							for (var i = 0; i < resp.datos.length; i++) {

								if(resp.datos[i].estado == 'pendiente')
								{
									t.row.add( [ 
										resp.datos[i].id_pago,
										resp.datos[i].eps,
										resp.datos[i].valor,
										resp.datos[i].fechapago,
										resp.datos[i].estado,
										resp.datos[i].fechacreacion,
										resp.datos[i].usuario,
										'<div class="btn-group btn-group-xs" data-id="'+resp.datos[i].id_pago+'" role="group" aria-label="Small button group"><button data-nivel="1" data-nombre="Administrador" data-id="1" type="button" class="btn btn-success waves-effect edit-item"><i class="material-icons">edit</i></button><button data-nivel="1" data-nombre="Administrador" data-id="1" type="button" class="btn btn-danger waves-effect delete-item"><i class="material-icons">delete</i></button></div>'
										]).draw( false );
								}else
								{
									t.row.add( [ 
										resp.datos[i].id_pago,
										resp.datos[i].eps,
										resp.datos[i].valor,
										resp.datos[i].fechapago,
										resp.datos[i].estado,
										resp.datos[i].fechacreacion,
										resp.datos[i].usuario,
										'<div class="btn-group btn-group-xs" data-id="'+resp.datos[i].id_pago+'" role="group" aria-label="Small button group"><button data-nivel="1" data-nombre="Administrador" data-id="1" type="button" class="btn btn-success waves-effect edit-item"><i class="material-icons">edit</i></button><button data-nivel="1" data-nombre="Administrador" data-id="1" type="button" class ="btn btn-primary waves-effect show-item"><i class="material-icons">library_books</i></button><button data-nivel="1" data-nombre="Administrador" data-id="1" type="button" class="btn btn-danger waves-effect delete-item"><i class="material-icons">delete</i></button></div>'
										]).draw( false );

								}
								
							}

							$('#Modalnuevo').modal('hide');
						} else {
							t.row($('#tabla-pagos').parents('tr') ).clear().draw();
							swal("Importante!", "No se han encontrado registros para ese filtro, intenta nuevamente.", "info");
						}
						pagos.recargar();
					}
				});
			});
		},
		cargarModal: function()
		{
			$('.filtro').on("click", function(){
				$('#Modalnuevo').modal('show'); 
				pagos.Cargar();
				pagos.enviarDatos();
			});
			$('.add-payment').on("click", function(){

				pagos.Cargar();
				pagos.enviarDatos();
				window.location.href = "pages/pagos/nuevopago.php";  
			});
		},

		AgregarItem: function()
		{
			$('#tabla-pagos tbody').on('click', '.edit-item', function () {

				//idpago
				var id = $(this).parent().data('id');
				var estado = $(this).parents('tr').find("td:nth-child(5)").text();

				if(estado == "completado")
				{
					swal({title: "Al editar un pago en estado Completado se perderán los datos anteriores. ¿Está seguro de EDITAR el pago?",
							text: "",
							type: "warning",
							confirmButtonText: "Aceptar",
							showCancelButton: true,
							confirmButtonColor: "rgb(174, 222, 244)",

							closeOnConfirm: false
						}, function (isConfirm) {
							if (isConfirm) {
							
								window.location.href = "pages/pagos/editarpago.php?id="+id + "&estado=" + estado;  

							}
					});
				}else{
					window.location.href = "pages/pagos/editarpago.php?id="+id + "&estado=" + estado;  
				}
			});

			$('#tabla-pagos tbody').on('click', '.delete-item', function () {

				//idpago
				var id = $(this).parent().data('id');
				var estado = $(this).parents('tr').find("td:nth-child(5)").text();
				swal({title: "¿Está seguro que desea ELIMINAR el pago?",
						text: "",
						type: "warning",
						confirmButtonText: "Aceptar",
						showCancelButton: true,
						confirmButtonColor: "rgb(174, 222, 244)",

						closeOnConfirm: false
					}, function (isConfirm) {
						if (isConfirm) {

							$.ajax({
								url: 'pages/pagos/peticiones/peticiones.php',
								type: 'POST',
								data: {
									bandera: "borrar-pago",
									idpago: id,
									estado: estado
									
								},
								success: function (resp) {

									var resp = $.parseJSON(jQuery.trim(resp));;
									if (resp.salida === true && resp.mensaje === true) {
										swal({title: "Información",
											text: "Se ha eliminado el pago de manera exitosa!",
											type: "success",
											confirmButtonText: "Aceptar",
											showCancelButton: false,
											confirmButtonColor: "rgb(174, 222, 244)",
											closeOnConfirm: false
										}, function (isConfirm) {
											if (isConfirm) {
												window.location.reload();
												//window.location.href = "pages/pagos/gestionar.php";  
											}
										});

									} else {
										swal("", "Ha ocurrido un error, intenta nuevamente.", "error");
									}
								}
							});
						}
					});

			});

			$('#tabla-pagos tbody').on('click', '.show-item', function () {

				//idpago
				var id = $(this).parent().data('id');
				window.location.href = "pages/pagos/detallespago.php?id="+id;  

			});


		},
		MostrarDetalles : function()
		{
			
		}
	};
	$(document).ready(function () {

		pagos.inicio();

	});

});